import subprocess
from pathlib import Path

import pytest

# Lockfiles pin transitive package names and are regenerated by tooling.
_SKIP_FILES = {"package-lock.json", "uv.lock"}


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def _candidate_files():
    """Every tracked text file, from git itself.

    Scanning only what git tracks keeps untracked caches, scratch files and
    transcripts from failing the test on one machine but not in CI, and covers
    extensionless files such as Dockerfile that a suffix whitelist would miss.
    """
    root = _repo_root()
    try:
        listed = subprocess.run(
            ["git", "ls-files", "-z"],
            cwd=root,
            capture_output=True,
            check=True,
        ).stdout
    except (OSError, subprocess.CalledProcessError):
        pytest.skip("not a git checkout; this guard runs where the repository is")

    for relative in listed.decode("utf-8", errors="ignore").split("\0"):
        if not relative:
            continue
        path = root / relative
        if path.name in _SKIP_FILES or path.name == Path(__file__).name:
            continue
        if not path.is_file():
            continue
        with path.open("rb") as handle:
            if b"\0" in handle.read(8192):
                continue  # binary
        yield path


def test_repository_contains_no_supabase_reference() -> None:
    """Phase 2B removes Supabase. This test keeps it removed.

    A stray reference means either dead code or, worse, a live credential
    surface for a service the product no longer uses.
    """
    offenders = []
    for path in _candidate_files():
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if "supabase" in text.lower():
            offenders.append(str(path.relative_to(_repo_root())))

    assert offenders == [], f"Supabase references remain in: {offenders}"


def test_untracked_local_files_do_not_trip_the_guard() -> None:
    """Only what is committed matters.

    Scanning the whole disk made any untracked scratch file, cache or
    transcript that mentions the word fail this test on one machine and not in
    CI, and inside the backend image the walk would start at /.
    """
    probe = _repo_root() / "zz_untracked_guard_probe.md"
    probe.write_text("supabase\n", encoding="utf-8")
    try:
        flagged = {p.name for p in _candidate_files()}
    finally:
        probe.unlink()
    assert "zz_untracked_guard_probe.md" not in flagged


def test_extensionless_tracked_files_are_scanned() -> None:
    """Dockerfile is where VITE_SUPABASE_* build arguments used to live."""
    names = {p.name for p in _candidate_files()}
    assert "Dockerfile" in names
