import type { ResearchRun } from '../types/research';

const baseVersions = {
  response_schema: 'research-run-response-v1' as const,
  workflow: 'eod-research-v1' as const,
  metrics: 'eod-metrics-v1' as const,
  policy: 'research-policy-v1' as const,
  code: 'git-commit-hash-test',
};

export const informationalRun: ResearchRun = {
  run_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
  symbol: 'AAPL',
  created_at: '2026-09-14T10:00:00Z',
  completed_at: '2026-09-14T10:00:02Z',
  as_of: '2026-09-11T20:00:00Z',
  workflow_status: 'succeeded',
  research_status: 'informational',
  summary: 'All required EOD price and news criteria are satisfied with sufficient quality.',
  reasons: [
    {
      code: 'EOD_COMPLETE',
      label: 'Sufficient Data & Signals',
      severity: 'info',
      description: 'All 21 trading sessions verified with fresh market and news coverage.',
      metric_keys: ['return_20d', 'volatility_20d', 'avg_dollar_volume_20d'],
      evidence_ids: ['ev-001'],
      policy_version: 'research-policy-v1',
      threshold: null,
    },
  ],
  metrics: [
    {
      key: 'return_20d',
      label: '20-Session Return',
      value: 0.0452,
      unit: 'ratio',
      window_sessions: 20,
      as_of: '2026-09-11T20:00:00Z',
      calculation_version: 'eod-metrics-v1',
      quality: 'fresh',
    },
    {
      key: 'volatility_20d',
      label: '20-Session Volatility',
      value: 0.2215,
      unit: 'ratio',
      window_sessions: 20,
      as_of: '2026-09-11T20:00:00Z',
      calculation_version: 'eod-metrics-v1',
      quality: 'fresh',
    },
    {
      key: 'avg_dollar_volume_20d',
      label: '20-Session Avg Dollar Volume',
      value: 12500000000,
      unit: 'usd',
      window_sessions: 20,
      as_of: '2026-09-11T20:00:00Z',
      calculation_version: 'eod-metrics-v1',
      quality: 'fresh',
    },
    {
      key: 'session_count',
      label: 'Completed Sessions Evaluated',
      value: 21,
      unit: 'count',
      window_sessions: 21,
      as_of: '2026-09-11T20:00:00Z',
      calculation_version: 'eod-metrics-v1',
      quality: 'fresh',
    },
  ],
  data_quality: {
    overall: 'sufficient',
    prices: 'fresh',
    news: 'fresh',
    model: 'healthy',
  },
  sources: [
    {
      evidence_id: 'ev-001',
      provider: 'yfinance',
      publisher: 'Reuters',
      title: 'Apple Expands Services Revenue in Recent Quarter',
      url: 'https://example.com/news/apple-services',
      event_time: '2026-09-11T14:30:00Z',
      retrieved_at: '2026-09-14T10:00:01Z',
      content_hash: 'abc123hash',
      source_type: 'news',
    },
  ],
  warnings: [],
  model_info: {
    provider: 'google',
    model: 'gemini-2.5-flash',
    prompt_version: 'research-interpretation-v1',
    failure_code: null,
  },
  versions: baseVersions,
  error_code: null,
  error_message_safe: null,
};

export const reviewRun: ResearchRun = {
  run_id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
  symbol: 'AAPL',
  created_at: '2026-09-14T10:05:00Z',
  completed_at: '2026-09-14T10:05:02Z',
  as_of: '2026-09-11T20:00:00Z',
  workflow_status: 'succeeded',
  research_status: 'review',
  summary: 'Research status is review due to AI interpretation failure.',
  reasons: [
    {
      code: 'MODEL_FAILED',
      label: 'Model Failure',
      severity: 'warning',
      description: 'AI interpretation unavailable',
      metric_keys: [],
      evidence_ids: [],
      policy_version: 'research-policy-v1',
      threshold: null,
    },
  ],
  metrics: [
    {
      key: 'return_20d',
      label: '20-Session Return',
      value: -0.0123,
      unit: 'ratio',
      window_sessions: 20,
      as_of: '2026-09-11T20:00:00Z',
      calculation_version: 'eod-metrics-v1',
      quality: 'fresh',
    },
    {
      key: 'volatility_20d',
      label: '20-Session Volatility',
      value: 0.185,
      unit: 'ratio',
      window_sessions: 20,
      as_of: '2026-09-11T20:00:00Z',
      calculation_version: 'eod-metrics-v1',
      quality: 'fresh',
    },
  ],
  data_quality: {
    overall: 'degraded',
    prices: 'fresh',
    news: 'fresh',
    model: 'failed',
  },
  sources: [
    {
      evidence_id: 'ev-002',
      provider: 'yfinance',
      publisher: 'Bloomberg',
      title: 'Tech Stocks Mixed Ahead of Fed Decision',
      url: 'https://example.com/news/tech-mixed',
      event_time: '2026-09-11T16:00:00Z',
      retrieved_at: '2026-09-14T10:05:01Z',
      content_hash: 'def456hash',
      source_type: 'news',
    },
  ],
  warnings: ['AI interpretation unavailable; showing quantitative metrics only.'],
  model_info: {
    provider: 'google',
    model: 'gemini-2.5-flash',
    prompt_version: 'research-interpretation-v1',
    failure_code: 'MODEL_UNAVAILABLE',
  },
  versions: baseVersions,
  error_code: null,
  error_message_safe: null,
};

export const insufficientRun: ResearchRun = {
  run_id: 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33',
  symbol: 'AAPL',
  created_at: '2026-09-14T10:10:00Z',
  completed_at: '2026-09-14T10:10:02Z',
  as_of: '2026-09-11T20:00:00Z',
  workflow_status: 'succeeded',
  research_status: 'insufficient_data',
  summary: 'Research status is insufficient_data because required price history is missing or stale.',
  reasons: [
    {
      code: 'PRICE_INSUFFICIENT',
      label: 'Insufficient Price History',
      severity: 'blocking',
      description: 'Required 21 valid completed closes could not be retrieved.',
      metric_keys: ['return_20d', 'volatility_20d'],
      evidence_ids: [],
      policy_version: 'research-policy-v1',
      threshold: 21,
    },
  ],
  metrics: [
    {
      key: 'return_20d',
      label: '20-Session Return',
      value: null,
      unit: 'ratio',
      window_sessions: 20,
      as_of: '2026-09-11T20:00:00Z',
      calculation_version: 'eod-metrics-v1',
      quality: 'missing',
    },
    {
      key: 'volatility_20d',
      label: '20-Session Volatility',
      value: null,
      unit: 'ratio',
      window_sessions: 20,
      as_of: '2026-09-11T20:00:00Z',
      calculation_version: 'eod-metrics-v1',
      quality: 'missing',
    },
  ],
  data_quality: {
    overall: 'insufficient',
    prices: 'missing',
    news: 'missing',
    model: 'not_run',
  },
  sources: [],
  warnings: ['Missing required price history.'],
  model_info: null,
  versions: baseVersions,
  error_code: null,
  error_message_safe: null,
};

export const failedMarketRun: ResearchRun = {
  run_id: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44',
  symbol: 'AAPL',
  created_at: '2026-09-14T10:15:00Z',
  completed_at: '2026-09-14T10:15:01Z',
  as_of: null,
  workflow_status: 'failed',
  research_status: 'failed',
  summary: null,
  reasons: [],
  metrics: [],
  data_quality: null,
  sources: [],
  warnings: [],
  model_info: null,
  versions: baseVersions,
  error_code: 'MARKET_DATA_FAILED',
  error_message_safe: 'Market data provider returned an error.',
};

export const historicalRun: ResearchRun = {
  ...informationalRun,
  run_id: 'e0eebc99-9c0b-4ef8-bb6d-6bb9bd380a55',
  created_at: '2026-08-01T15:30:00Z',
  as_of: '2026-07-31T20:00:00Z',
};
